### ISSUE TITLE
When replying/forwarding original encrypted message is quoted

### ISSUE THREAD

**Issue by rithiv** [barrydegraaff/pgp-zimlet#107]
I'm, sorry if this has been already reported, but I couldn't find it in the list of issues or the online help.

Situation: You receive an encrypted message, and decrypting it in the preview pane works fine.

Issue: when replying the encrypted message is quoted.

Expected result:
Reply quotes the decrypted message

Workaround: copy message from preview pane and paste it in reply "window" or tab whatever Zimbra calls it. But that's kind of a messy "solution".

See attached image for my current reply/forward settings.

![zimbra_preferences](https://cloud.githubusercontent.com/assets/7603389/8961791/a306f46e-3617-11e5-9f70-9df4f433a1f6.png)

**Comment by barrydegraaff** [comment]
3 possible solutions:

1. Add additional reply button, next to the additional print button
2. Extend or temporary replace the function that is behind the build in Zimbra buttons (see attachment reminder Zimlet for sample implementation)
3. (Add an option to) store the message in unencrypted form on the server and leave the buttons alone.

**Comment by barrydegraaff** [comment]
When doing option 1, this may break the conversation view.

**Comment by barrydegraaff** [comment]
https://wiki.zimbra.com/wiki/Zimlet_cookbook_based_on_JavaScript_API#How_to_add_additional_functionality_to_an_.2Aexisting.2A_toolbar_button

**Comment by barrydegraaff** [comment]
While this is a good idea, implementing this will take me at least 2 days.

And there probably will be a lot of bugs and trial and error, i won't be coding this any time soon.

**Comment by barrydegraaff** [comment]
This has been implemented a few releases back.
