### ISSUE TITLE
Dashes are inserted in the message body

### ISSUE THREAD

**Issue by JusticeRage** [barrydegraaff/pgp-zimlet#109]
Hello, and thanks for your Zimlet - I use it a lot.
I have encountered what seems like a bug to me: when I try to sign the following message:

```
​Test 
----

- This is a test
```

The following message is generated:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Test
 - ----

 - - This is a test
-----BEGIN PGP SIGNATURE-----
Version: OpenPGP.js v1.0.1
Comment: http://openpgpjs.org

wsFcBAEBCAAQBQJV047NCRBA6fCo9eqHVAAAnLcQAKGwU/c14VYdJsqcfLcT
kU+owdKVU6BiQpP5AJD7CKxlxYSjLFOfmKTMZH9xz0JWw/ESnNMLIZ02hkvE
uba+HU9AWj0oEGGfPeI+vs3/5YXDFyenRBSdy2cXuoA58ug+W/RDVgh1g34J
WOHXrvAEXDCEfXTx0Vtm4wlmA6Ol1cfkrMZrrCAxa3jcOC61x4If1VKmJCil
8IHAv90Q19Qodhbm2ZYRLw7IRnVJf4FsbEZk4yDMlySZ/MZ9vIFzRX1mJEV2
Ze0XkwieZN6wwTrtboK1C3PXsDxRZexbdNMfsxV67kRItSjdDIhLV/sv4+qb
KgCXXZvlq4wud/fDQa0vdPlwdPvQKDvcLcT2LS+sYiJ+23VUjML20G2lv7Cu
Lc9h0ofiETA3YDl+0teHG137LqqPJgMiJzozzAqRksfmkRL5b3ryiiX+tR/B
CNtNJlmw6iKml6KetswHvlKTS4oJ6WAxObEcKyZHwVoM5CbsW3Lm9+Eu9pco
4V7jqChUnZX36aDJjVpisRYGQUh47BZgbXjzjDlSH6Wv7G+MMPr1Iig0x5bp
2ne8kXyNRB14Ovqyzc1l/Bt9NEsqlKrOlZyCjzp3vQ+vLSW4qpBD5YnHXef4
h2dYt+I0uTMHMiDeGDGwW/AuOoP9OTqQX/PUg+Fm3Phn+LuFl5eiJSfs85I2
xY0L
=BFMz
-----END PGP SIGNATURE-----
```

I assume that this is a security measure to prevent users from interfering with the `-----BEGIN PGP SIGNATURE-----` tag, but should any line starting with a dash be escaped? This limits formatting options a lot for plain e-mails.

**Comment by barrydegraaff** [comment]
The escaping of dashes has been added on purpose. It is something GnuPG does as well.

That aside a few 'bugs' are in openpgp.js that would make a message containing a dash on a newline unable to be verified.

https://github.com/openpgpjs/openpgpjs/issues/317
https://github.com/openpgpjs/openpgpjs/issues/311

So the zimlet also removes spaces at the end of your message.

Maybe you can use * or ' - ' space dash for your formatting.

Thanks Barry

**Comment by JusticeRage** [comment]
You are right - I hadn't realized GPG was doing this as well. After further research, I found out that this is necessary to sign text which may contain another PGP signature.
It seems to me that only`-----END PGP SIGNATURE-----` would need to be escaped, but in any case that's outide of the zimlet's scope.

I apologize for the erroneous bug report!

**Comment by barrydegraaff** [comment]
No problem, happy with your feedback

**Comment by barrydegraaff** [comment]
For documentation purpose, the above behavior is according to RFC4880 under 
7.1.  Dash-Escaped Text 

https://tools.ietf.org/html/rfc4880#section-7
