### ISSUE TITLE
Decryption Only Works with Reading Pane On?

### ISSUE THREAD

**Issue by MattMencel** [barrydegraaff/pgp-zimlet#110]
Been messing around with this zimlet.  Is it the case that it only works with the Reading Pane?  If the Reading Pane is off and I double click an encrypted message, or open in new window, it seems the message doesn't get decrypted.

Maybe I'm just doing it wrong?

Matt

**Comment by barrydegraaff** [comment]
That is indeed how it works now.

Date: Thu, 20 Aug 2015 14:32:22 -0700

**Comment by barrydegraaff** [comment]
If you want, I can build integration into the opened message as you describe (if you would be able to donate a bit to this project).

  
  



Of course, I also am happy to merge any PR you might create.
Most every day use cases are in the video here http://www.barrydegraaff.tk/
