### ISSUE TITLE
Improvement of public key management

### ISSUE THREAD

**Issue by jafeha** [barrydegraaff/pgp-zimlet#111]
hey barry! After a very long time i just re-tested the pgp-zimlet and i must say, i'm really, really impressed. :) i like the implementation and at least for me, it works like a charme with zimbra 8.6.0 patch 3. 

but one thing i'd really appreciate is a simplified public key management. i'd suggest two features:

* import keys form public servers
* import public key rings

i'm not sure if this sould be adressed here in the pgp-zimlet or in openpgp.js. have you spend any thoughts on features like that?

**Comment by barrydegraaff** [comment]
A lot of times that question has been asked, but I do not trust key servers. As there is no good way (for an end-user) to determine the authenticity of the public key (fingerprint and all).
So I always tell my users to exchange the keys in person.
On the other hand 'import keys form public servers' has been built already in jsp. So it wouldn't be very hard, again a smalldonation would do wonders.

import public key ringsThat one is not going to work, as you probably are talking about a gnupg file that is a binary. And javascript has a hard timereading binaries. Also this is indeed an openpgp.js feature... and there is already a discussion about that (they are notgoing to do it from the looks of it). 

Thank you very much for your feedback, it is much appreciated.

Barry

**Comment by jafeha** [comment]
You're probably right about keyservers, it's not really a good idea to rely totally on public key servers. i always tell my users to verify fingerprints, no matter where they got their keys from. as a matter of fact i periodically use key servers whenever i haven't any public key for a user prior to initiating contact with that person. So i'd use the feature every now and then. 

About importing keyrings: what i had in mind was not importing the binary keyring rather than an ascii armored keyring. this might be a bit tricky to build (haven't found the right gpg switch yet), but rather than exporting / copying one key at a time, this would be much, much easier. 

Having said all this: this is great work you've done and i'm considering a donation even though i'd need donations myself finishing my university degree.

**Comment by barrydegraaff** [comment]
Keyserver support has been added in 2.2.6
https://github.com/Zimbra-Community/pgp-zimlet#keyserver-lookup

**Comment by barrydegraaff** [comment]
It is now possible to export loads of public keys and copy-paste them in one go to pgp-zimlet, see:
https://barrydegraaff.github.io/help/#thunderbird-enigmail-export

Additionally all key server interactions have been added as well.
