### ISSUE TITLE
Disable LDAP private password storage globally

### ISSUE THREAD

**Issue by jafeha** [barrydegraaff/pgp-zimlet#112]
I really dislike the idea of storing user passwords in plain text within our LDAP even though the private key is stored in a local user storage. So i see two possibilities improving the users' security:

* adding an option for disabling the storage of passwords in LDAP globally (i have no idea if thats possible within zimbra zimlets)
* storing the password optionally within the client (which might be even worse storing the key and passwort within the same storage)

have you spend any thoughts about that before? i see the aspect of usability within the feature, but i'd at least like to have an option for turning it off globally.

**Comment by barrydegraaff** [comment]
> adding an option for disabling the storage of passwords in LDAP globallyThat is a good idea and I have heard that question before, but right now it is not on the roadmap.I am willing to  build such a feature for a donation, or am happy to merge your PR if you are into coding.
> storing the password optionally within the clientThis feature is already in pgp-zimlet, the passphrase that is stored on the client is aes encrypted, with the AESpassword on the server. Same for the private key, so it is not that easy to get something of the client, ifthe client is not logged onto zimbra.
Also whenever the password is stored on the server it is hashed, not the same as plain-text, but close.An admin cannot read it accidentally but someone on the server with admin power could use the AES password(also in the ldap) to unhash the passphrase.

**Comment by barrydegraaff** [comment]
> adding an option for disabling the storage of passwords in LDAP globally
That is a good idea and I have heard that question before, but right now it is not on the roadmap.
I am willing to  build such a feature for a donation, or am happy to merge your PR if you are into coding.

> storing the password optionally within the client
This feature is already in pgp-zimlet, the passphrase that is stored on the client is aes encrypted, with the AES password on the server. Same for the private key, so it is not that easy to get something of the client, if the client is not logged onto zimbra.

Also whenever the password is stored on the server it is hashed, not the same as plain-text, but close.
An admin cannot read it accidentally but someone on the server with admin power could use the AES password (also in the ldap) to unhash the passphrase.

**Comment by jafeha** [comment]
* As i haven't done any js/zimlet coding, just some random python coding and as i'm currently writing my dissertation i can't send you any PR right now. And i wouldn't feel to good starting coding js close to any encryption software ;) 

* i'll have a closer look at the passwort storage within the client, i hadn't seen that feature by now. 

* about hashed passwords: i hadn't even tested this password saving feature as i did not even want to save my own pw on my own server ;) i just read the comment / warning about the passwords being stored in plain text (which is great btw, other coders won't give a damn, store it in plain text and won't warn the users) and thought it would be a good idea to switch off that option completely.

* About donating: as i said, i'm a student, writing my dissertation and running my own zimbra server without having any real income right now. so i'm really not sure if i can afford an donation / paying you for implementing these features. things might change within the next year but until then i can't afford huge donations. if you could send me a PM about what it might cost i could ask some friends about collecting a possibly larger donation. no promisses, but i'd try to find some money for this improvement here and the ones suggested in #111

**Comment by barrydegraaff** [comment]
I am sorry, was in a hurry, I said hashing, off course I meant encoding/decoding.

**Comment by barrydegraaff** [comment]
I am happy that you like the warning message about the plain text password storing. Cause that is basically what it is.

The password storing was also something a lot of people wanted, and all the precautions I took building this combined, makes that, I believe, the Zimlet has the right balance between usability and security.

**Comment by barrydegraaff** [comment]
So a fun exercise to do for you is, store a dummy private key and passphrase in your browsers local storage. Then try to find that key and passphrase in your browsers profile.

That gives you a lot more insight :-p
