### ISSUE TITLE
recognize public keys in mail / send public keys

### ISSUE THREAD

**Issue by chrissi5120** [barrydegraaff/pgp-zimlet#114]
Hi Barry,

Had just some ideas about tuning the public key management:

- a button that opens a dialogue to send your public key to someone, just a small box with an send or okay button in the dropdown menu from that zimlet

- if you receive a Public Key from someone, it should open up a window for example which allows you to check the certificate and import it if you like what you are seeing

It sounds strange, but it would dramatically increase the haptic of that zimlet.

This weekend I configured PGP for a few people on my Server. Everyone finds it to tricky to copy and paste all the time. The General Encrypt and Sign haptic is a piece of cake even for my older relatives :+1:

**Comment by barrydegraaff** [comment]
Those are good suggestions! I will add them to the next version.

Barry
________________________________

**Comment by barrydegraaff** [comment]
@chrissi5120 I have added the following new features:
1. Whenever a plain text email is received that contains a readable public key armored block, a dialog is show asking the user to import the new key. A context help link has been added to explain fingerprint verification.

2. A menu option (Zimlet menu lift bottom) has been added `Send someone my public key`, it opens a new plain text formatted message with the users public key.

If possible please git-clone the current version and submit a test report:
https://github.com/barrydegraaff/pgp-zimlet/blob/master/test/checklist-for-testing.pdf
and
https://github.com/barrydegraaff/pgp-zimlet/blob/master/test/

Thanks, Barry
