### ISSUE TITLE
1.7.6 Throws 404 error when accessing the help menu

### ISSUE THREAD

**Issue by chrissi5120** [barrydegraaff/pgp-zimlet#119]
HTTP ERROR 404

Problem accessing /zimlet/_dev/tk_barrydegraaff_zimbra_openpgp/help/index.html. Reason:

Not Found

**Comment by barrydegraaff** [comment]
Sorry, that is a packaging bug in the zip file... I will release a new one, in a minute...

**Comment by barrydegraaff** [comment]
I have released a new version, 1.7.7 to fix this broken package, you can now download it from Zimbra Gallery: https://www.zimbra.org/extend/items/view/zimbra-openpgp-zimlet

Sorry for the inconvenience. Barry
