### ISSUE TITLE
Upgrade to 1.7.6 seems to kill the core functionality

### ISSUE THREAD

**Issue by chrissi5120** [barrydegraaff/pgp-zimlet#120]
After upgrade I am unable to:

- open the context menu(s)
     "Manage Keys" does not open
    "sign Message" opens the sign window, but clicking okay does not give feedback/hung up
    "encrypt Message" does nothing at all
    "Generate keys" wasnt clicked in order to not kill my existing configuration :)
    "send someone my key" opens like it should a new composing tab containg my key"

- decrypt/encrypt/sign Mail

does not work at all

**Comment by barrydegraaff** [comment]
it is just a packaging failure on my part, please upgrade to 1.7.7

Date: Sat, 5 Sep 2015 09:25:32 -0700

**Comment by chrissi5120** [comment]
check, 1.7.7 works fine right now, i will look deeper ! :)

**Comment by barrydegraaff** [comment]
Sorry, that is a packaging bug in the zip file...

I have released a new version, 1.7.7 to fix this broken package, you can now download it from Zimbra Gallery: https://www.zimbra.org/extend/items/view/zimbra-openpgp-zimlet

Sorry for the inconvenience. Barry

**Comment by barrydegraaff** [comment]
I will create a script to make sure, it cannot happen again...

**Comment by barrydegraaff** [comment]
https://github.com/barrydegraaff/pgp-zimlet/issues/121
