### ISSUE TITLE
Import PGP key glitch

### ISSUE THREAD

**Issue by chrissi5120** [barrydegraaff/pgp-zimlet#122]
Sometimes the PGP import feature offers me to import keys already listed in the configuration

It imports again and works just fine. 

The only issue is that I have the same key at slot 2 and slot 8 for example

It offers the import infinitely that you can go fill slot 9,10,11 with the exact same key

edit:

the issue seem to appear if you send somebody your Public key and sign it direclty that you have this structure:

------BEGIN PGP SIGNED MESSAGE-----
------BEGIN PGP PUBLIC KEY BLOCK-----
------END PGP PUBLIC KEY BLOCK-----
------BEGIN PGP SIGNATURE-----
------END PGP SIGNATURE-----

**Comment by barrydegraaff** [comment]
The import feature currently only checks if there is a free public key slot and if what you are importing is a valid key.

I have not build a check for duplicates yet.

It would be based on comparing fingerprints, not very hard...

**Comment by chrissi5120** [comment]
I think that's a thing it should have

It does no harm to any data or something but it improves the haptic in general

You do a great job, really, the only thing I could report right now is a very minor issue :+1: 

The new version in general is very good accepted under the not so techie guys !

**Comment by barrydegraaff** [comment]
Fixed in commit
https://github.com/barrydegraaff/pgp-zimlet/commit/9852b24a82847c2f61e04f24d79e1af0463e00eb
