### ISSUE TITLE
refine key generation

### ISSUE THREAD

**Issue by chrissi5120** [barrydegraaff/pgp-zimlet#125]
Hi,

I just thought about the key generation process.. 

It's pretty straight Forward that you just hit generate key pair and all that Magic happens.

But maybe you can refine that process like this:

NEW:

- When you hit the generate key pair button a window wops up
- It offers you 2 things, "automatically generate keys for me" OR "fill in personal info"

CHANGE:

- beside choosing the key size it should be possible to define how long the key is valid for usage

This is pretty much just nice to have of course.. BUT with this you don't even think about using tools like gpg4win. 

As always just my few thoughts :)

best regards from your neighbor Germany 

Christoph

**Comment by barrydegraaff** [comment]
Well I don't really see the added value of hiding even more details from the end-user (point 1 and 2), so I probably won't build that.

Also the Zimlet does not check expiry date / or revocation, in my opinion those things are for the user to decide upon. Also it would make things look more complicated for new users, so I probably won't build that either.

Sorry
