### ISSUE TITLE
Wrong DwtHtmlEditor?

### ISSUE THREAD

**Issue by JeroenKool** [barrydegraaff/pgp-zimlet#128]
Love the idea on PGP in Zimbra, but upon deployment in Zimbra 8.6.0_GA_1153 (build 20141215195814) I get:

 ReferenceError: DwtHtmlEditor is not defined 

Upon loading the Zimbra Web Client, and the public key admin page does not show

**Comment by barrydegraaff** [comment]
What version of PGP Zimlet did you install and did you install patch 2 on your Zimbra server?

Please run from zimbra as user zimbra: zmprov fc all

And make sure to remove your browsers temporary files.

**Comment by JeroenKool** [comment]
think i used 1.7.4, tried again with 1.7.8, seems to be OK there. 

thanks 



JEROEN KOOL 
VCAP/MCITP/MCSE/PMP/ITIL/MASE 

Partner - Integrative.it 



APAC : 70-72 Avenido de Sidonia Pais / The Phoenix Terrace 40A / Macau SAR 
US/LATAM : 2220 Meridian Blvd, Suite S5435, Minden NV 89423 
EU: 151 Rastenfeld, 3532 Rastenfeld, Austria 

Web : http://www.integrative.it / www.legal-it.net 
tel HK: +852 58049082 / US: +1 352 353 0001 
cell HK : +852 69727221 / MO: +853 66551551 
Skype: Integrative.it 




Reseller for : Hewlett Packard,SuperMicro,VMware,Microsoft,Zimbra,Zextras,Nexenta,Brocade

**Comment by barrydegraaff** [comment]
Okay thanks for reporting, I like to introduce my new crowd-funding effort:

The Zimbra OwnCloud Zimlet
https://www.indiegogo.com/projects/zimbra-owncloud-extension-zimlet

Please help me get the buzz out, and Share it!

Thanks and best regards,

Barry

**Comment by JeroenKool** [comment]
shared. although personally i'd rather see some alfresco integration. 




JEROEN KOOL 
VCAP/MCITP/MCSE/PMP/ITIL/MASE 

Partner - Integrative.it 



APAC : 70-72 Avenido de Sidonia Pais / The Phoenix Terrace 40A / Macau SAR 
US/LATAM : 2220 Meridian Blvd, Suite S5435, Minden NV 89423 
EU: 151 Rastenfeld, 3532 Rastenfeld, Austria 

Web : http://www.integrative.it / www.legal-it.net 
tel HK: +852 58049082 / US: +1 352 353 0001 
cell HK : +852 69727221 / MO: +853 66551551 
Skype: Integrative.it 




Reseller for : Hewlett Packard,SuperMicro,VMware,Microsoft,Zimbra,Zextras,Nexenta,Brocade

**Comment by barrydegraaff** [comment]
In a few moments I will share an update on the Zimbra ownCloud Zimlet in that it will support
WebDAV, so this Zimlet will support much more systems then only ownCloud.

Barry
