### ISSUE TITLE
I don't see "sign" or "encrypt" buttons in compose email window

### ISSUE THREAD

**Issue by kevinkretz** [barrydegraaff/pgp-zimlet#133]
Hi - 

I installed the zimlet and made it available to my account; when I log in I see "OpenPGP" under "Zimlets".  I create keys as on the help page, but when I start a new message I do not see "sign message" or "encrypt message" buttons.

I'm running zimbra 8.6.

thanks 

Kevin

**Comment by barrydegraaff** [comment]
Maybe a cache issue, can you try in development mode, add ?dev=1 after

  
  


yourZCSserver.com/?dev=1
That should be very slow, but if it works, it means you have a cache issue.
zmprov fc allzmmailboxdctl restart
and flush your browser.

If it is not a cache issue, can you press F12 in your browser and see if there areany error messages in the console.
You can also use all functionality from OpenPGP Zimlet from the Zimlet menu, the onethat you already found.

**Comment by kevinkretz** [comment]
This is on a different browser because I'm at home now - but still firefox.  I still do not get the buttons in dev mode.  I cleared my cache anyway and tried again - still no buttons. Tried Chrome too.

In console, no error messages after "Loading package: Zimlet" - but after "Loading package: Extras" there's a line "unreachable code after return segment".

**Comment by barrydegraaff** [comment]
please flush the server cache, 

  
  



zmprov fc allzmmailboxdctl restart
The unreachable code thing, is not an issue.

**Comment by kevinkretz** [comment]
Flushed cache + restarted, no change.

**Comment by barrydegraaff** [comment]
I have not seen this before .

Did you install other non standard zimlets?

Do you compose in a new window? That does not work.

Do you have network edition?
________________________________

**Comment by kevinkretz** [comment]
I am composing in new window.  I didn't see that restriction in the help.  It appears as expected now - sorry to have wasted your time!

**Comment by barrydegraaff** [comment]
OpenPGP Zimlet should have disabled that option, you probably found a loop-hole somewhere.
Also this does not work because of a very old bug in Zimbra

**Comment by barrydegraaff** [comment]
See:https://bugzilla.zimbra.com/show_bug.cgi?id=97496
