### ISSUE TITLE
Decrypt messages from gmail using mailvelope (plain-text inside html)

### ISSUE THREAD

**Issue by mkauzlar** [barrydegraaff/pgp-zimlet#134]
Hi, I'm receiving pgp encrypted emails which have in the subject: "\*\*\*UNCHECKED\*\*\*"
Something like:

Subject: \*\*\*UNCHECKED\*\*\* test pgp2

Body:
-----BEGIN PGP MESSAGE-----

.....

-----END PGP MESSAGE-----

How do I decrypt these messages?
I can see the "Encrypt" and "Sign" buttons when I compose an email and those works however there is no "Decrypt" command in received emails.

**Comment by barrydegraaff** [comment]
They are automatically decrypted in the reading pane, you should not open/double click these emails to open

**Comment by mkauzlar** [comment]
I'm afraid they are not encrypted in the reading pane. They just stay there encrypted

**Comment by barrydegraaff** [comment]
Are you sure the messages are formatted as plain/text messages, also try and make sure there is not a bunch of text before the PGP MESSAGE block.

Maybe a cache issue, can you try in development mode, add ?dev=1 after
yourZCSserver.com/?dev=1

That should be very slow, but if it works, it means you have a cache issue.

zmprov fc allzmmailboxdctl restart
and flush your browser.

**Comment by mkauzlar** [comment]
Thanks for the prompt reply.

it was indeed a HTML formatted email although with fixed width font and you couldn't tell it was html. 

The email was sent from gmail using mailvelope. One needs to go into the gamil options of the sending mail in order to change to plain text. Once this is done decryption works on zimbra.

Thanks for your quick support :-)

However I don't see people changing the default email setting in order to send an email to someone because they just don't know if the recipient is on zimbra or not.
If it's not possible to decrypt emails that are not formatted as text perhaps a warning from the zimlet should come saying the email is not text formatted and it can't decrypt it. This way a user can reply to the sender saying to change his sending option.

**Comment by barrydegraaff** [comment]
For the record, I think sending out PGP ASCII armored messages inside HTML is a poor implementation. It SHOULD have been avoided.

https://github.com/mailvelope/mailvelope/issues/41#issuecomment-29423044

Its probably mailvelope cannot change the message type to text from Gmail, this is what happens if you go in the cloud, and the API of your cloud provider is poor. (A programmer can do this in Zimbra or any other non cloud based service)

Anyway, I will look into it.

**Comment by barrydegraaff** [comment]
Should be handled in onMsgView see comment:
//not a plain text message and no PGP mime, means no PGP

**Comment by barrydegraaff** [comment]
Can you send a message from gmail with mailvelope using public key: https://raw.githubusercontent.com/barrydegraaff/pgp-zimlet/master/test/dummy-keypair.txt

and send it to bgraaff@hivos.org

Thanks you

**Comment by barrydegraaff** [comment]
Its actually better than I assumed, the PGP message is in multipart/alternative mime part.

I expect to support this soon

**Comment by mkauzlar** [comment]
Sent with HTML format

**Comment by mkauzlar** [comment]
"I expect to support this soon"
Thanks :-)

**Comment by barrydegraaff** [comment]
@mkauzlar Gmail Mailvelope should now be read correctly by Zimbra OpenPGP Zimlet.

If you have the time, please test the version from git:
https://github.com/barrydegraaff/pgp-zimlet/wiki

And send us a test report:
https://github.com/barrydegraaff/pgp-zimlet/blob/master/test/checklist-for-testing.pdf

If not, then OpenPGP Zimlet will be tested in a week or so and a new version with
this fix will be release.

Thanks for your feedback, Barry

**Comment by mkauzlar** [comment]
I created the dev environment as per wiki. I don't know how to build and
install (sorry, I'm not a developer)
If you give me some tips I can go on. Thanks

**Comment by barrydegraaff** [comment]
First make sure to undeploy OpenPGP Zimlet if you installed it before using zmzimletctl:

      su zimbra
      zmzimletctl undeploy tk_barrydegraaff_zimbra_openpgp

Then as root:

      cd /tmp
      rm pgp-zimlet -Rf
      git clone https://github.com/barrydegraaff/pgp-zimlet
      cd pgp-zimlet
      ./install-dev.sh

**Comment by barrydegraaff** [comment]
you should install git, using yum install git or apt-get install git

**Comment by mkauzlar** [comment]
Ok, intalled it.

Here is the progress:
HTML emails from gmail are now recognized as encrypted and a password
request is displayed for the private key. Also the arrived email
displays:

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)

Here are the problems:
Both HTML and text encrypted emails are now not decrypted. I'm asked
for the password but then nothing happens.

**Comment by barrydegraaff** [comment]
Yeah that is a cache issue

Flush your browser cache, restart your server, start your browser again and all should be fine.

**Comment by mkauzlar** [comment]
It didn't help. I restarted the server and used another browser which never
logged into zimbra, still the same

**Comment by barrydegraaff** [comment]
Try and use a different account.

**Comment by mkauzlar** [comment]
I created a new account for testing in zimbra
Switched PC and browser
Still the same

You can try it yourself with the email I sent you from gmail earlier

**Comment by barrydegraaff** [comment]
Yeah it works fine here...

**Comment by mkauzlar** [comment]
ok, will undeploy and install again and report back

**Comment by mkauzlar** [comment]
I did:

$ zmzimletctl undeploy tk_barrydegraaff_zimbra_openpgp
[] INFO: Uninstalling Zimlet tk_barrydegraaff_zimbra_openpgp from LDAP.
[] INFO: undeploying zimlet tk_barrydegraaff_zimbra_openpgp
[] INFO: zimlet directory tk_barrydegraaff_zimbra_openpgp is deleted
$ zmcontrol restart

However openpgp is still there in my email interface

**Comment by barrydegraaff** [comment]
That is becuase you probably installed it in dev now, if you want to remove:

  
  


rm -Rf  /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_zimbra_openpgp/

Then after installing using the steps above, reboot your server.
If it still does not work, I think I need an account on your server to debug

**Comment by mkauzlar** [comment]
ok, here is what I did:

A:
1. Undeployed and removed
2. Restarted server
3. Deployed
4. Restarted server
5. Tested email - No go

B:
1. Undeployed and removed
2. Restarted server
3. Deployed official 1.8 version
4. Restarted server
5. Tested email - No go but then - When I clicked the encrypted email, the
popup for the paraphrase showed up and instead of clicking ok I pressed
enter by habit.
This actually moves the email to a separate tab (instead of staying on the
mail tab) and there was hanging. All I could do is press back in the
browser to get the mouse back.
Then I tried again and it worked!! Now works every time.
But this was back the 1.8.0 version wich doesn't work with HTML so:

C:
1. Undeployed and removed
2. Restarted server
3. Deployed git version
4. Restarted server
5. Tested email - No go
Then I tried the hack again by pressing enter instead of ok.
Now it works with the new version as well.

I suppose there is an issue there with the popup for password and
subsequent rendering of the message.
For instance one should be able to press <enter> after the passphrase in
order to have it decrypted. But then, this allowed the email moved to it's
own tab which in turn made openpgp work afterwards.
Not sure if all this is a coincidence or not. Perhaps you have the
passphrase stored so it doesn't prompt you, so your use case is different?

**Comment by barrydegraaff** [comment]
Yep pressing enter does not do what you expect, you should press the OK button.

  
  



Does it work then?

**Comment by mkauzlar** [comment]
yes it does
