### ISSUE TITLE
ZWC cannot automatically decrypt message with reading pane mode "Off"

### ISSUE THREAD

**Issue by thangnguyennang** [barrydegraaff/pgp-zimlet#135]
Users using Zimbra Web Client/ZWC click the encrypted message (double click), the Zimlet does not automatically decrypt the message in a new tab (users still see the encrypted message).
This error happens if setting reading pane mode "Off", the Zimlet works normally with the reading panes "At The Bottom" or "On The Right" (it automatically decrypts the message).
Note:
* Zimbra version: ZCS 8.6, 64-bit
* Zimlet version: latest version (deployed in _dev mode)

**Comment by barrydegraaff** [comment]
Yes, it is not an error, it just has never been implemented, also it is currently not scheduled to be.

**Comment by thangnguyennang** [comment]
@barrydegraaff thanks for your information.
