### ISSUE TITLE
Internationalization i18n

### ISSUE THREAD

**Issue by barrydegraaff** [barrydegraaff/pgp-zimlet#19]
http://wiki.zimbra.com/wiki/ZCS_6.0:Zimlet_Developers_Guide:Internationalization

Is someone wants to work on this, let me know!

**Comment by barrydegraaff** [comment]
Please remember that there are a LOT of issues with i18n,

The Zimbra way is:
http://wiki.zimbra.com/wiki/Zimlet_Developers_Guide:Internationalization
Naming your Zimlet Handler Object the same as your Zimlet Name will cause sporadic results. Be sure to name the Handler Object something different than your zimlet name. For example, the Handler Object for a zimlet named "com_zimbra_helloworld" should be "com_zimbra_helloworldHandlerObject". See Zimlet Handler Object for more information.

Also internationalisation will require to use the Zimlet with zmzimletctl deploy OR log in with ?dev=1 
the latter is TOO SLOW!

I would prefer being able (have the option) to use _dev folder for deployment. But l18n is not applied in _dev... so stuff would show up as $sometext1 instead of "The content of some text 1"

So maybe we should implementing our own version of i18n... just a JavaScript function or class or whatever, just keep it in mind if you ever make a pull request, that I will not accept a solution that breaks using the Zimlet from _dev folder.

Maybe file a Zimbra bug to have i18n in _dev?

**Comment by barrydegraaff** [comment]
https://bugzilla.zimbra.com/show_bug.cgi?id=97708

Please vote

**Comment by tuanta** [comment]
I am planning to start working on this in the next two weeks too (during my Lunar new year holidays).
Any work done before? Need to work from beginning?

**Comment by barrydegraaff** [comment]
You may want to consider waiting for news on bug https://bugzilla.zimbra.com/show_bug.cgi?id=97708

If not, you may follow the wiki http://wiki.zimbra.com/wiki/Zimlet_Developers_Guide:Internationalization

Or build your own javascript functions (detect user language) and apply our own i18n funtions.

Just remember if you make a pull request, I will not accept a solution that breaks using the Zimlet from _dev folder.

**Comment by barrydegraaff** [comment]
To-do: remove Zimlet Panel menu from definition XML and add it to javascript code like this:
http://community.zimbra.com/collaboration/f/1885/t/1077468

To-do: remove all gui-text from the javascript code and make a template for translation

To-do: add zimlet option to change interface language

**Comment by tuanta** [comment]
@barrydegraaff I can start working on this in the next a few days. Is that ok?

**Comment by barrydegraaff** [comment]
You can translate the vietnamese, I will alter the rest of the code for i18n support tomorrow.

Truong Anh Tuan <notifications@github.com> wrote:

@barrydegraaff I can start working on this in the next a few days. Is that ok?

---

**Comment by tuanta** [comment]
> You can translate the vietnamese, I will alter the rest of the code for i18n support tomorrow.

Thanks @barrydegraaff . I am planning to work on this issue (to add i18n support, not just Vietnamese translation) in my Tet holidays in next a few days. However, if you are also working on now, I will wait.

**Comment by barrydegraaff** [comment]
I am starring now...

**Comment by barrydegraaff** [comment]
i18n implemented, deployed a zip with 1.4.9 version to test server, and did all the tests from the test script in dutch language.

It works!
