### ISSUE TITLE
Max key size limit 5120

### ISSUE THREAD

**Issue by Gummikavalier** [barrydegraaff/pgp-zimlet#33]
Hi,

There seems to be a limit in max size of the key.

We got following error when trying to add CERT-FI advisory signing key to the list of public keys:

--------------------------
An unknown error (account.INVALID_ATTR_VALUE) has occurred.
method:	[unknown]
msg:	zimbraZimletUserProperties value length(6304) larger than max allowed: 5120
code:	account.INVALID_ATTR_VALUE
detail:	soap:Sender
trace:	qtp1610155881-522456:https://86.50.27.101:443/service/soap/ModifyPropertiesRequest:1402926385487:a14dd2ad8032661d
request:	

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><context xmlns="urn:zimbra"><userAgent xmlns="" name="ZimbraWebClient - FF30 (Linux)" version="8.0.7_GA_6021"/><session xmlns="" id="1436433"/><notify xmlns="" seq="2"/><account xmlns="" by="name">toharkon@csc.fi</account><format xmlns="" type="js"/></context></soap:Header><soap:Body><ModifyPropertiesRequest xmlns="urn:zimbraAccount"><prop xmlns="" zimlet="tk_barrydegraaff_zimbra_openpgp" name="zimbra_openpgp_pubkeys1">-----BEGIN PGP PUBLIC KEY BLOCK-----
...
-----END PGP PUBLIC KEY BLOCK-----</prop><prop xmlns="" zimlet="tk_barrydegraaff_zimbra_openpgp"

------------------------------

The key we tested with was:
https://www.viestintavirasto.fi/attachments/tietoturva/pgpavaimet/CERT-FI_Advisory_Signing_Key_2013.txt

Software versions:
Zimbra NE 8.0.7
Zimbra OpenPGP Zimlet 1.0.0 from gallery.zimbra.com

**Comment by alanwds** [comment]
Hi,

We have the same problem. My zimbra version is 8.6.0_GA_1178 (build 20150618170638).

I read the readme.md file, but there are nothing about it.

I'm missing something?

Thanks

**Comment by barrydegraaff** [comment]
Edit zimbra-attrs.xml like this:

As root:

nano /opt/zimbra/conf/attrs/zimbra-attrs.xml
Find the line:
name="zimbraZimletUserProperties" type="cstring" max="5120"
and change it to
name="zimbraZimletUserProperties" type="cstring" max="15120"

then zmcontrol restart

The value will be increased for ZCS 8.7 but since that is delayed, I will put this back in the readme tomorrow

**Comment by barrydegraaff** [comment]
added to the readme once again

**Comment by barrydegraaff** [comment]
See also:
https://bugzilla.zimbra.com/show_bug.cgi?id=96823

Verified fixed in Zimbra 8.7.0_BETA1_1294 (build 20150801180818)
