### ISSUE TITLE
Could not read armored message!

### ISSUE THREAD

**Issue by Lemmork** [barrydegraaff/pgp-zimlet#56]
Hi,

I have a server which sends encrypted messages to me. But if I try to decrypt these messages I get a "Could not read armored message!"-Error.
The server encrypt the text with
PHP/Pear Package “Crypt_GPG” >= 1.3.x
gnupg binary 1.4.x

Are there compatibility issues? And if there are issues with the compatibility is it possible to fix them?

**Comment by barrydegraaff** [comment]
Sure, please post the message source of an example of your problematic message to https://gist.github.com/ 

Then we will look into it, also consider a donation http://www.barrydegraaff.tk/donate

**Comment by barrydegraaff** [comment]
Also try to drag and drop the message onto the Zimlet panel icon (left bottom of Window). That may give better results.

**Comment by Lemmork** [comment]
Thanks for your answer, d'n'd does not help. Do you need the encrypted message?
At the moment I completly broke my system. So I'm not able to send it at the moment.

**Comment by barrydegraaff** [comment]
Please post the encrypted message source OR let your server send a test message to info at barrydegraaff dot tk.

Thanks

**Comment by Lemmork** [comment]
OK system is alive again, please find it there:
https://gist.github.com/Lemmork/5aae0f651027285a0298

I additionally added the private and public key I tested with. 

I tried using GnuPG1 and 2, both with the same effect.
Here is the debug-Output of the generating GnuPG1 run:
https://gist.github.com/Lemmork/7f0da9b391a0b67b8cfa

**Comment by barrydegraaff** [comment]
Your PGP MESSAGE is garbled, therefore it does not work, so some system on your end is not plapying nicely with CRLF or LF or whatever.

Your message should be in the form of:
​​​​​-----BEGIN PGP MESSAGE-----
Version: OpenPGP.js v0.9.0
Comment: http://openpgpjs.org

wYwDIauWoQjwCBABA/0V2cQfsWRsnEAmrD9jc0GL9Nm9HH9d8IKaiOzygP0h
hcYUGO8RyZMuvReVcdMnedlNQrN6swDK/pQ3a8z+lm7pvnJyXfW2t/KqtqVG
ibhKC+zHldRxxLsmSwovSpz/SPdaHF2xYd/C+V1uDQu7ewoUay7XHbmoAcyR
WPHPmJfO1dLAKQHK2u8pYOP8RgvFT5b7HRt8TQOqjIIK3TOqfZlNp0xoxecC
UVERQsZlx1PQi14hagSXg/R9CKjwBwzmRzT0GKOFX85sTW5RHbu2vB5SPRqD
dyi3/845EHKvDrQ2yq+wyP4XhjJtYdQFJ2CeRYqrketBNb4bwAYk4a0gAi3D
8ZXkDdGxqMHSEZERFdecfjxqYKiuuq041e+gp2KUPFAHjxTsDlplX9wDX9qn
gsU33sqdqEEfGMcBg777Xhm7iXppoIumJju8DQuXRGumAgVnQF06gGsFk8lo
utufxM7tev0AMxGJEGGrN1D5
=wzf9
-----END PGP MESSAGE-----

The message is NOT on a single line!!!

Not an opoenpgp.js issue

**Comment by barrydegraaff** [comment]
https://gist.github.com/barrydegraaff/e4b65b5066bd0808ab56
