### ISSUE TITLE
Cannot send without sign

### ISSUE THREAD

**Issue by maxxer** [barrydegraaff/pgp-zimlet#66]
1. Compose a new message
2. Choose Encrypt
3. Leave the *optional* passphrase field empty, as you just want to crypt and not to sign

Result: error message saying passphrase is not valid.
If it can matter when the dialog opens the Private Key field is populated, while the passphrase isn't (didn't store it).

**Comment by barrydegraaff** [comment]
Well, this is how it is designed,

The passphrase option is only optional if there is no private key in the the dialog (pasted by the user or via cache).

So right now, you need to clear your private key.

You may propose a different solution....

**Comment by maxxer** [comment]
you assume that since the key is not blank the user intend to also sign the message, right?

this problem has been reported to me by a new zimlet user, but long time gpg one. 
since the signing is optional he expected it to be so. if the passphrase is empty I'd rather not give error and just crypt the message. what do you think?

**Comment by barrydegraaff** [comment]
That is a good idea, I will implement it tomorrow!

Date: Tue, 31 Mar 2015 09:20:01 -0700

**Comment by barrydegraaff** [comment]
Fixed in commit https://github.com/barrydegraaff/pgp-zimlet/commit/971a4d6934576b15d52fb8eaa3e91baf0147c79c
