### ISSUE TITLE
Encrypt private key in browsers local storage

### ISSUE THREAD

**Issue by barrydegraaff** [barrydegraaff/pgp-zimlet#69]
So I like to add a 'feature' to encrypt the users private key if the user has opted to store the private key in the html5 local storage.

Because this:
sqlite3 '/home/user/.config/google-chrome/Default/Local Storage/https_mail.domain.com_0.localstorage'
SQLite version 3.8.8.3 2015-02-25 13:29:11
Enter ".help" for usage hints.
sqlite> .tables
ItemTable
sqlite> select * from ItemTable
   ...> ;
undefined|10:40fd4a8a-7390-4dab-9335-e205e0f9b290:10
zimbra_openpgp_privatekeyuser@domain.com|-----BEGIN PGP PRIVATE KEY BLOCK-----
Version: GnuPG v1

Is not secure at all, if a users PC gets compromised, or if there is a bug in the browser.

For example, we could generate an additional PGP keypair, store it (pubkey, privkey and passphrase) on the server and ONLY use it to decrypt the local storage html5 privkey for this zimlet.

@tuanta can you fix this?

1. When a user stores data to html5 localstore, encrypt it with newly generated keypair, that is ALWAYS on the server.
2. Alert existing users, with a  this.status( in case they still have an unencrypted privkey, and provide an option for them to encrypt it now.
3. Be aware, localstore privkey is an array, there can be multiple users using the same PC/browser that can use the same Zimbra server and not be in each others way.

Am I being paranoid?

@tuanta please let me know!

**Comment by barrydegraaff** [comment]
maybe we should make this an optional feature, or use a low key length (1024) or use another algorithm?

**Comment by tuanta** [comment]
Yes, you are right. It should be encrypted. We can make it optional, but enable by default.
Because we are planning to put all public/private keys and passphrase of this new keypair on the same place (server), I think we can use a symmetric algorithm instead of an asymmetric one.
What do you think?

**Comment by barrydegraaff** [comment]
Yes symmetric encryption may perform much better and is more suitable for the job, if you can find something that works cross-browser and that doesnot require too much js includes. That would be nice.
It may take some research on your part though.
Barry


Date: Fri, 10 Apr 2015 02:49:02 -0700

**Comment by barrydegraaff** [comment]
https://keybase.io/triplesec
a 300kB library, but does what we need

**Comment by barrydegraaff** [comment]
https://code.google.com/p/jscryptolib/

**Comment by barrydegraaff** [comment]
Have not yet checked the licenses, @tuanta before you include a library, please check if it is compatible with GNU GPL v3

**Comment by tuanta** [comment]
@barrydegraaff sorry, I am so busy these days so I have not got much time to back to this issue.
I will start studying it this weekend.

**Comment by barrydegraaff** [comment]
This one:
http://www.movable-type.co.uk/scripts/aes.html
Looks like a very small library, and also it is an open standard and open-source software

**Comment by barrydegraaff** [comment]
Github for the AES above, author says it is a reference implementation ...
https://github.com/chrisveness/crypto/blob/master/aes.js

**Comment by tuanta** [comment]
Thanks @barrydegraaff. Seems the last one is best for us. I will have some early hacks tomorrow morning.

**Comment by barrydegraaff** [comment]
@tuanta great, Browser support looks great, and license MIT is also compatible.
https://github.com/chrisveness/crypto

@tuanta 
Maybe you can read the current privatekey in prototype.init or //Constructor
tk_barrydegraaff_zimbra_openpgp = function() {

and then encrypt it for existing users, using a call to

tk_barrydegraaff_zimbra_openpgp.prototype.localStorageSave
(modify localStorageSave to include AES)

The key is read using:
 tk_barrydegraaff_zimbra_openpgp.privateKeyCache = localStorage['zimbra_openpgp_privatekey'+tk_barrydegraaff_zimbra_openpgp.prototype.getUsername()];
	   
You should create a new function:
tk_barrydegraaff_zimbra_openpgp.prototype.localStorageRead to replace all :
localStorage['zimbra_openpgp_privatekey'+tk_barrydegraaff_zimbra_openpgp.prototype.getUsername()];

Good luck!

**Comment by barrydegraaff** [comment]
Also add a new variable to the settings json to store the aes password on the server:
tk_barrydegraaff_zimbra_openpgp.settings['aespassword'] = (generate password with tk_barrydegraaff_zimbra_openpgp.prototype.pwgen)

And then call:
 this.setUserProperty("zimbra_openpgp_options", JSON.stringify(tk_barrydegraaff_zimbra_openpgp.settings), false);


Also for ease of programming, add a variable to the local store, to indicate the private key was encrypted with aes-chrisveness

So if we must, we can replace the AES in a future version, if it breaks.

I hope the above is a little bit clear, but also tomorrow I will be on IRC should you have any questions.

Thanks

**Comment by barrydegraaff** [comment]
fixed in
https://github.com/barrydegraaff/pgp-zimlet/commit/a59042980008c53c46960a8b0f31bac60f46b25a

The localStore sqlite3 database now looks like this:
sqlite> select * from ItemTable;
undefined|10
zimbra_openpgp_privatekeyadmin@myzimbra.com|jwD9Ih7KNFVrKgus9...nMBNBLrlntRtg2w==
zimbra_openpgp_privatekeybarry@myzimbra.com|YgHw367KNFUqDpzyE...RRvPhhM=
sqlite>

**Comment by barrydegraaff** [comment]
released patch in version 1.5.8
