### ISSUE TITLE
[openpgpjs] Signing messages with Trailing Whitespace results in GOT A BAD SIGNATURE #311

### ISSUE THREAD

**Issue by barrydegraaff** [barrydegraaff/pgp-zimlet#77]
When a user tries to sign a message but (accidentally) adds one or more whitespaces at the end of the message, the signature verification fails.

**Comment by barrydegraaff** [comment]
This bug is also in version 1.5.4 so it has been in the code for at least 2 months

**Comment by barrydegraaff** [comment]
Also in 1.2.9, the first version that supports ZCS 8.6, so this bug was here since December 2014 at least.

I did got some issues reported by users that they had issues with signing, just was never able to confirm.

Also this does not seem to bother most users, a bug still.

**Comment by barrydegraaff** [comment]
https://github.com/mailvelope/mailvelope/issues/254

**Comment by barrydegraaff** [comment]
https://github.com/openpgpjs/openpgpjs/issues/311

**Comment by barrydegraaff** [comment]
In theory I can alter the source message and strip trailing spaces, but this is evil an bad practice,

so I am going to leave this open for a week or so, and see if it gets picked up.

**Comment by tuanta** [comment]
I think any modifications after message signed must not be allowed (or it would lead to break the signuture).

**Comment by barrydegraaff** [comment]
@tuanta see https://github.com/barrydegraaff/pgp-zimlet/commit/24173e0d12c1f5d62f119e641c6f97c9681941ee

This issue is fixed, but a similar bug is also present when using html compose...
